{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "dragonfly.fullname" . }}-metrics
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- end }}
  labels:
    chart: {{ template "dragonfly.chart" . }}
    app: {{ template "dragonfly.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.serviceMonitor.labels }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
      honorLabels: true
      port: {{ default "metrics" .Values.service.metrics.portName }}
      path: /metrics
      scheme: http
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      {{- include "dragonfly.selectorLabels" . | nindent 6 }}
      type: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
